redesign the multighc travis configuration

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,75 +1,46 @@
 env:
-  - GHCVER=7.6.3
-  - GHCVER=7.8.4
-  - GHCVER=7.10.1
-  - GHCVER=head
+ - GHCVER=7.6.3 CABALVER=1.16
+ - GHCVER=7.8.4 CABALVER=1.18
+ - GHCVER=7.10.1 CABALVER=1.22
+ - GHCVER=head CABALVER=1.22
 
 matrix:
   allow_failures:
-    - env: GHCVER=head
+   - env: GHCVER=head CABALVER=1.22
 
 before_install:
-  # If $GHCVER is the one travis has, don't bother reinstalling it.
-  # We can also have faster builds by installing some libraries with
-  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
-  # with cabal-1.18.
-  - |
-    if [ $GHCVER = `ghc --numeric-version` ]; then
-      # Try installing some of the build-deps with apt-get for speed.
-      travis/cabal-apt-install --enable-tests $MODE
-      export CABAL=cabal
-    else
-      # Install the GHC we want from hvr's PPA
-      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
-      travis_retry sudo apt-get update
-      travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
-      export CABAL=cabal-1.18
-      export PATH=/opt/ghc/$GHCVER/bin:$PATH
-    fi
-  # Uncomment whenever hackage is down.
-  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
-  - $CABAL update
-
-  # Update happy when building with GHC head
-  - |
-    if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.4" ] || [ $GHCVER = "7.10.1" ]; then
-      $CABAL install --constraint=transformers\ installed happy alex
-      export PATH=$HOME/.cabal/bin:$PATH
-    fi
-  - git clone https://github.com/ekmett/bifunctors.git
-  - cd bifunctors
-  - $CABAL install
-  - cd ..
-  - git clone https://github.com/ekmett/semigroupoids.git
-  - cd semigroupoids
-  - $CABAL install
-  - cd ..
-  - git clone https://github.com/ekmett/profunctors.git
-  - cd profunctors
-  - $CABAL install
-  - cd ..
-  - $CABAL install --only-dependencies
+ - git clone https://github.com/ekmett/bifunctors.git
+ - git clone https://github.com/ekmett/profunctors.git
+ - git clone https://github.com/ekmett/semigroupoids.git
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+ - cabal --version
 
 install:
-  - $CABAL install --dependencies-only --enable-tests
-  - $CABAL configure --enable-tests $MODE
+ - travis_retry cabal update
+ - cd bifunctors
+ - cabal install
+ - cd ../profunctors
+ - cabal install
+ - cd ../semigroupoids
+ - cabal install
+ - cd ..
+ - cabal install --enable-tests --only-dependencies
 
 script:
-  - $CABAL build
-  - $CABAL test --show-details=always
-
-  # tests that a source-distribution can be generated
-  - $CABAL sdist
-
-  # check that the generated source-distribution can be built & installed
-  - export SRC_TGZ=$($CABAL info . | awk '{print $2 ".tar.gz";exit}') ;
-    cd dist/;
-    if [ -f "$SRC_TGZ" ]; then
-       $CABAL install --force-reinstalls "$SRC_TGZ";
-    else
-       echo "expected '$SRC_TGZ' not found";
-       exit 1;
-    fi
+ - cabal configure -v2 --enable-tests
+ - cabal build
+ - cabal sdist
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
 
 notifications:
   irc:
